### ISSUE TITLE
Encountered exception in Trail Menu

### ISSUE THREAD

**Issue by DrHappyBro** [DSH105/SparkTrail#2]
Hello!

So I have problem with Trail Menu, when I open it and choose an effect it just gives me a error log:

[13/03/2014]---[14:46:33][SparkTrail] §c[SEVERE] Encountered exception in Trail Menu
java.lang.ArrayIndexOutOfBoundsException: -999
    at org.bukkit.craftbukkit.v1_7_R1.inventory.CraftInventoryCustom$MinecraftInventory.getItem(CraftInventoryCustom.java:61)
    at org.bukkit.craftbukkit.v1_7_R1.inventory.CraftInventory.getItem(CraftInventory.java:49)
    at com.dsh105.sparktrail.menu.MenuListener.onInvClick(MenuListener.java:171)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:471)
    at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:1361)
    at net.minecraft.server.v1_7_R1.PacketPlayInWindowClick.a(SourceFile:32)
    at net.minecraft.server.v1_7_R1.PacketPlayInWindowClick.handle(SourceFile:10)
    at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:146)
    at net.minecraft.server.v1_7_R1.ServerConnection.c(SourceFile:134)
    at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:655)
    at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250)
    at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545)
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457)
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617)

[13/03/2014]---[14:46:57][SparkTrail] §c[SEVERE] Encountered exception in Trail Menu
java.lang.ArrayIndexOutOfBoundsException

[13/03/2014]---[14:56:32][SparkTrail] §c[SEVERE] Encountered exception in Trail Menu
java.lang.ArrayIndexOutOfBoundsException

I would highly appreciate if someone could tell me what causes this error.
Thank you!

**Comment by DSH105** [comment]
Is that happening when you click the item or when you click outside the menu?

**Comment by DrHappyBro** [comment]
It happens when I click something inside a menu.

**Comment by DSH105** [comment]
Fixed :). Also expect updates to this to roll out sometime soon.

**Comment by DrHappyBro** [comment]
Alright, thank you! :)
